### PR TITLE
Bail out of static rendering for pages and routes in app dir

### LINKED ISSUE #1356: next build failing with missing environment variables
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm running `next build` against a fresh repo generated with the create next app and am running into build errors due to missing Auth0 environment variables.

It seems that this is because I don't have a `.env.local` with the environment variables specified there.
Why do I need this? These will be provided at runtime, so am confused as to why they are failing build steps.

I followed these two issues which seem to have fixed this, but I am not seeing that.
* https://github.com/auth0/nextjs-auth0/issues/154
* https://github.com/auth0/nextjs-auth0/pull/255

```
npm run build             

> my-app@0.1.0 build
> next build

- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types  
- info Collecting page data ..TypeError: "secret" is required
    at get (/Users/nick/code/playground/my-app/.next/server/chunks/877.js:367:15)
    at getConfig (/Users/nick/code/playground/my-app/.next/server/chunks/877.js:1664:45)
    at getInstance (/Users/nick/code/playground/my-app/.next/server/chunks/877.js:2744:63)
    at handleAuth (/Users/nick/code/playground/my-app/.next/server/chunks/877.js:2791:31)
    at 83739 (/Users/nick/code/playground/my-app/.next/server/app/api/auth/[auth0]/route.js:126:32)
    at __webpack_require__ (/Users/nick/code/playground/my-app/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/Users/nick/code/playground/my-app/.next/server/app/api/auth/[auth0]/route.js:172:39)
    at /Users/nick/code/playground/my-app/.next/server/app/api/auth/[auth0]/route.js:173:78
    at __webpack_require__.X (/Users/nick/code/playground/my-app/.next/server/webpack-runtime.js:138:21)
    at /Users/nick/code/playground/my-app/.next/server/app/api/auth/[auth0]/route.js:173:47

> Build error occurred
Error: Failed to collect page data for /api/auth/[auth0]
    at /Users/nick/code/playground/my-app/node_modules/next/dist/build/utils.js:1156:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
- info Collecting page data .%     
```

### Reproduction

1. npx create-next-app@latest
2. Add `/app/api/auth/[auth0]/route.ts` file with the recommended setup.
3. `npm run build`

You can skip the first two steps by cloning my repo here: https://github.com/nickzelei/auth0-bug
Running `npm run build` results in an error due to missing environment variables.

This can be fixed by adding a basic `.env.local` file
```
AUTH0_SECRET=replace-with-your-own-secret-generated-with-openssl
AUTH0_BASE_URL=http://localhost:3000
AUTH0_ISSUER_BASE_URL='https://example.com'
AUTH0_CLIENT_ID='{CLIENT_ID}'
AUTH0_CLIENT_SECRET='{CLIENT_SECRET}'
AUTH0_AUDIENCE=
AUTH0_SCOPE='openid profile'
```

### Additional context

_No response_

### nextjs-auth0 version

3.1.0

### Next.js version

13.4.13

### Node.js version

18.16.0

### PR DESCRIPTION
**Pull request by adamjmcgrath**
### 📋 Changes

Ensure `getConfig` doesn't run when the Next.js app is being statically rendered (because static rendering happens at build time and users don't necessarily want to supply the config at build time)

The 2 large commits are for making sure the config can be lazily evaluated at request time (`config` -> `getConfig(req)`):

- 30c100e3fdaa00be4d627f84351e3421d9829243 allow lazy config in auth0-session 
- d79ff8f59accdf0535d616ae80dc57de343317e9 allow lazy config in Next.js layer

The 3rd small commit is using this to bail out of static rendering before getting the config.

bec7d6c5998ba06ae87cb906235d7568bab2418f - Bail out of static rendering for pages and routes in app dir

You can bail out of static rendering by using the `cookies()` helper for Server Components and inspecting the request's `url` for API routes

### 📎 References

fixes #1356 
https://github.com/vercel/next.js/issues/49006

### 🎯 Testing

- Make sure you have no environment variables
- Run "npm run build:example"
- You should see no errors

### CODE REVIEW

**Comment by adamjmcgrath** [comment]
Investigating an issue with the edge client

**Comment by dominicfallows** [comment]
This works great for my projects - tested on several. Thanks for sorting this, hopefully this can be made official soon?

File: src/session/get-access-token.ts [hunk 1]
```diff
@@ -226,13 +229,16 @@ export type GetAccessToken = (
...
-  config: NextConfig,
-  client: AbstractClient,
+  getConfig: GetConfig,
+  getClient: GetClient,
   sessionCache: SessionCache
 ): GetAccessToken {
   return async (reqOrOpts?, res?, accessTokenRequest?): Promise<GetAccessTokenResult> => {
     const options = (res ? accessTokenRequest : reqOrOpts) as AccessTokenRequest | undefined;
     const req = (res ? reqOrOpts : undefined) as IncomingMessage | NextApiRequest | undefined;
+    // TODO: clean up
```
Comment (ewanharris) [inline src/session/get-access-token.ts:239]: Should this be removed or is there work to do?

**Review by ewanharris — COMMENTED** [review]
Just a minor comment around the todo

File: src/session/get-access-token.ts (hunk 1 above)
Comment (adamjmcgrath) [reply src/session/get-access-token.ts:239]: Ah yep, will remove that comment

Comment (adamjmcgrath) [reply src/session/get-access-token.ts]: ed41013

**Review by ewanharris — APPROVED** [review]
