### PR TITLE
Should be able to set rollingDuration as false (when rolling is false)

### LINKED ISSUE #591: "session.rollingDuration" must be false when "session.rolling" is disabled
I'm trying to disable session rolling by setting in config:
```js 
session: {
    absoluteDuration: 60 * 60 * 8,
    rollingDuration: 0,
    rolling: false,
},
```
But accidentally I'm getting compile error:
> "session.rollingDuration" must be false when "session.rolling" is disabled

If I write as proposed:
```js 
session: {
    absoluteDuration: 60 * 60 * 8,
    rollingDuration: false,
    rolling: false,
},
```
I'm getting TS error:
`TS2322: Type 'boolean' is not assignable to type 'number'.  config.d.ts(171, 5): The expected type comes from property 'rollingDuration' which is declared here on type 'DeepPartial<SessionConfig>'`

### PR DESCRIPTION
**Pull request by adamjmcgrath**
### Description

The types for `rollingDuration` don't match the run time checks that Joi does.

You should be able to set `rollingDuration` as `false` (when `rolling` is `false`)

### References

fixes #591 

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `main`

### CODE REVIEW

File: src/auth0-session/cookie-store.ts [hunk 1]
```diff
@@ -70,12 +70,12 @@ export default class CookieStore {
     const { rolling, rollingDuration } = this.config.session;
 
     if (typeof absoluteDuration !== 'number') {
-      return uat + rollingDuration;
+      return uat + (rollingDuration as number);
```
Comment (adamjmcgrath) [inline src/auth0-session/cookie-store.ts:73]: This is enforced at runtime by Joi

**Review by Widcket — APPROVED** [review]
